name: CI

on: push

jobs:

  build: 
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps: 


      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up Python 3.9
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
      
      - name: install python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install -e . 

      - name: test with Pytest
        run: |
         pytest --cov=inflammation.models tests/test_models.py
          
      